### Fetch a transaction and parse Jupiter swaps from it
GET http://localhost:3000/parse-jupiter-swaps?signature=4KHPmpbkv28HfhzR1gM1szgtpqg2CLhQo4eo1tD8qctWE4ULYw7fPKuNWPwJjszdq3qin526dC3iYBhcYbragwou

### Parse Jupiter swaps from the transaction passed in the body

POST http://localhost:3000/parse-jupiter-swaps-from-transaction
Content-Type: application/json

{
  "blockTime": 1718975806,
  "meta": {
    "computeUnitsConsumed": 105527,
    "err": null,
    "fee": 755000,
    "innerInstructions": [
      {
        "index": 2,
        "instructions": [
          {
            "parsed": {
              "info": {
                "extensionTypes": [
                  "immutableOwner"
                ],
                "mint": "So11111111111111111111111111111111111111112"
              },
              "type": "getAccountDataSize"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 2
          },
          {
            "parsed": {
              "info": {
                "lamports": 2039280,
                "newAccount": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
                "owner": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
                "source": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
                "space": 165
              },
              "type": "createAccount"
            },
            "program": "system",
            "programId": "11111111111111111111111111111111",
            "stackHeight": 2
          },
          {
            "parsed": {
              "info": {
                "account": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6"
              },
              "type": "initializeImmutableOwner"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 2
          },
          {
            "parsed": {
              "info": {
                "account": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
                "mint": "So11111111111111111111111111111111111111112",
                "owner": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo"
              },
              "type": "initializeAccount3"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 2
          }
        ]
      },
      {
        "index": 5,
        "instructions": [
          {
            "accounts": [
              "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "HYz1naua3Qo4M1SJEPAsZLV9yUfqHoi4FRDwjf6g87bL",
              "J7hnE4PRq7T6sbLTJpiKEPgumMZcMc63bhXD8usiWA4V",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
              "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
              "4PdcTtgYA6kR6FkCiBjKHz5xHxfsA6NsU1ktMkV5BEuj",
              "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo"
            ],
            "data": "6BPQkA7DGVXuVyBCsm2665D",
            "programId": "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
            "stackHeight": 2
          },
          {
            "parsed": {
              "info": {
                "amount": "10000000",
                "authority": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
                "destination": "HYz1naua3Qo4M1SJEPAsZLV9yUfqHoi4FRDwjf6g87bL",
                "source": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6"
              },
              "type": "transfer"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 3
          },
          {
            "parsed": {
              "info": {
                "amount": "1449869193",
                "authority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
                "destination": "4PdcTtgYA6kR6FkCiBjKHz5xHxfsA6NsU1ktMkV5BEuj",
                "source": "J7hnE4PRq7T6sbLTJpiKEPgumMZcMc63bhXD8usiWA4V"
              },
              "type": "transfer"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 3
          },
          {
            "accounts": [
              "D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf"
            ],
            "data": "QMqFu4fYGGeUEysFnenhAvR83g86EDDNxzUskfkWKYCBPWe1hqgD6jgKAXr6aYoEQaxoqYMTvWgPVk2AHWGHjdbNiNtoaPfZA4znu6cRUSWSeNwtcN63LaK3mEWBLRvQJpikxPx1cjQyuuJSgCJJbkGX6jR8Gjp5xg64H9hudeqeqs5",
            "programId": "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
            "stackHeight": 2
          }
        ]
      }
    ],
    "logMessages": [
      "Program ComputeBudget111111111111111111111111111111 invoke [1]",
      "Program ComputeBudget111111111111111111111111111111 success",
      "Program ComputeBudget111111111111111111111111111111 invoke [1]",
      "Program ComputeBudget111111111111111111111111111111 success",
      "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]",
      "Program log: CreateIdempotent",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
      "Program log: Instruction: GetAccountDataSize",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1569 of 109787 compute units",
      "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
      "Program 11111111111111111111111111111111 invoke [2]",
      "Program 11111111111111111111111111111111 success",
      "Program log: Initialize the associated token account",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
      "Program log: Instruction: InitializeImmutableOwner",
      "Program log: Please upgrade to SPL Token 2022 for immutable owner support",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 103200 compute units",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
      "Program log: Instruction: InitializeAccount3",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3158 of 99318 compute units",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
      "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 22315 of 118192 compute units",
      "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success",
      "Program 11111111111111111111111111111111 invoke [1]",
      "Program 11111111111111111111111111111111 success",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
      "Program log: Instruction: SyncNative",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3045 of 95727 compute units",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
      "Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 invoke [1]",
      "Program log: Instruction: Route",
      "Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 invoke [2]",
      "Program log: ray_log: A4CWmAAAAAAAAAAAAAAAAAACAAAAAAAAAICWmAAAAAAAhXDN3FIAAAAkvoVtDC8AAIk/a1YAAAAA",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]",
      "Program log: Instruction: Transfer",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4736 of 46627 compute units",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]",
      "Program log: Instruction: Transfer",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4645 of 38910 compute units",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
      "Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 consumed 29278 of 62964 compute units",
      "Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 success",
      "Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 invoke [2]",
      "Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 consumed 2025 of 30707 compute units",
      "Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 success",
      "Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 consumed 66219 of 92682 compute units",
      "Program return: JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 iT9rVgAAAAA=",
      "Program JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 success",
      "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]",
      "Program log: CreateIdempotent",
      "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 4437 of 26463 compute units",
      "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
      "Program log: Instruction: TransferChecked",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 6146 of 22026 compute units",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
      "Program log: Instruction: CloseAccount",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2915 of 15880 compute units",
      "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
    ],
    "postBalances": [
      2724328736,
      0,
      2039280,
      2039280,
      1,
      731913600,
      1,
      934087680,
      1141440,
      1461600,
      0,
      10121835540,
      6124800,
      355903808757,
      2039280,
      577538934826,
      1141440,
      4217265002
    ],
    "postTokenBalances": [
      {
        "accountIndex": 2,
        "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
        "owner": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "2726741564393",
          "decimals": 6,
          "uiAmount": 2726741.564393,
          "uiAmountString": "2726741.564393"
        }
      },
      {
        "accountIndex": 3,
        "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
        "owner": "ZG98FUCjb8mJ824Gbs6RsgVmr1FhXb2oNiJHa2dwmPd",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "967849245",
          "decimals": 6,
          "uiAmount": 967.849245,
          "uiAmountString": "967.849245"
        }
      },
      {
        "accountIndex": 13,
        "mint": "So11111111111111111111111111111111111111112",
        "owner": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "355901769477",
          "decimals": 9,
          "uiAmount": 355.901769477,
          "uiAmountString": "355.901769477"
        }
      },
      {
        "accountIndex": 14,
        "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
        "owner": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "51728973725339",
          "decimals": 6,
          "uiAmount": 51728973.725339,
          "uiAmountString": "51728973.725339"
        }
      }
    ],
    "preBalances": [
      2735083736,
      0,
      2039280,
      2039280,
      1,
      731913600,
      1,
      934087680,
      1141440,
      1461600,
      0,
      10121835540,
      6124800,
      355893808757,
      2039280,
      577538934826,
      1141440,
      4217265002
    ],
    "preTokenBalances": [
      {
        "accountIndex": 2,
        "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
        "owner": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "2725306199776",
          "decimals": 6,
          "uiAmount": 2725306.199776,
          "uiAmountString": "2725306.199776"
        }
      },
      {
        "accountIndex": 3,
        "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
        "owner": "ZG98FUCjb8mJ824Gbs6RsgVmr1FhXb2oNiJHa2dwmPd",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "953344669",
          "decimals": 6,
          "uiAmount": 953.344669,
          "uiAmountString": "953.344669"
        }
      },
      {
        "accountIndex": 13,
        "mint": "So11111111111111111111111111111111111111112",
        "owner": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "355891769477",
          "decimals": 9,
          "uiAmount": 355.891769477,
          "uiAmountString": "355.891769477"
        }
      },
      {
        "accountIndex": 14,
        "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
        "owner": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "uiTokenAmount": {
          "amount": "51730423594532",
          "decimals": 6,
          "uiAmount": 51730423.594532,
          "uiAmountString": "51730423.594532"
        }
      }
    ],
    "rewards": [],
    "status": {
      "Ok": null
    }
  },
  "slot": 273161452,
  "transaction": {
    "message": {
      "accountKeys": [
        {
          "pubkey": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
          "signer": true,
          "source": "transaction",
          "writable": true
        },
        {
          "pubkey": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
          "signer": false,
          "source": "transaction",
          "writable": true
        },
        {
          "pubkey": "4PdcTtgYA6kR6FkCiBjKHz5xHxfsA6NsU1ktMkV5BEuj",
          "signer": false,
          "source": "transaction",
          "writable": true
        },
        {
          "pubkey": "HhEBntRQGzaFBcav3wkCMk16pwHd8aHG1dCnJNF8Rom3",
          "signer": false,
          "source": "transaction",
          "writable": true
        },
        {
          "pubkey": "ComputeBudget111111111111111111111111111111",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "11111111111111111111111111111111",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "ZG98FUCjb8mJ824Gbs6RsgVmr1FhXb2oNiJHa2dwmPd",
          "signer": false,
          "source": "transaction",
          "writable": false
        },
        {
          "pubkey": "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
          "signer": false,
          "source": "lookupTable",
          "writable": true
        },
        {
          "pubkey": "HYz1naua3Qo4M1SJEPAsZLV9yUfqHoi4FRDwjf6g87bL",
          "signer": false,
          "source": "lookupTable",
          "writable": true
        },
        {
          "pubkey": "J7hnE4PRq7T6sbLTJpiKEPgumMZcMc63bhXD8usiWA4V",
          "signer": false,
          "source": "lookupTable",
          "writable": true
        },
        {
          "pubkey": "So11111111111111111111111111111111111111112",
          "signer": false,
          "source": "lookupTable",
          "writable": false
        },
        {
          "pubkey": "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
          "signer": false,
          "source": "lookupTable",
          "writable": false
        },
        {
          "pubkey": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
          "signer": false,
          "source": "lookupTable",
          "writable": false
        }
      ],
      "addressTableLookups": [
        {
          "accountKey": "GmvTb5XS7HcbHFTvruGvBF2VZzHBv9c6cKi8jn6dLsdh",
          "readonlyIndexes": [
            11,
            2,
            3
          ],
          "writableIndexes": [
            93,
            91,
            92
          ]
        }
      ],
      "instructions": [
        {
          "accounts": [],
          "data": "KjR8Zd",
          "programId": "ComputeBudget111111111111111111111111111111",
          "stackHeight": null
        },
        {
          "accounts": [],
          "data": "3nWLEMUsgdZR",
          "programId": "ComputeBudget111111111111111111111111111111",
          "stackHeight": null
        },
        {
          "parsed": {
            "info": {
              "account": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
              "mint": "So11111111111111111111111111111111111111112",
              "source": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
              "systemProgram": "11111111111111111111111111111111",
              "tokenProgram": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              "wallet": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo"
            },
            "type": "createIdempotent"
          },
          "program": "spl-associated-token-account",
          "programId": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
          "stackHeight": null
        },
        {
          "parsed": {
            "info": {
              "destination": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
              "lamports": 10000000,
              "source": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo"
            },
            "type": "transfer"
          },
          "program": "system",
          "programId": "11111111111111111111111111111111",
          "stackHeight": null
        },
        {
          "parsed": {
            "info": {
              "account": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6"
            },
            "type": "syncNative"
          },
          "program": "spl-token",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "stackHeight": null
        },
        {
          "accounts": [
            "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
            "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
            "4PdcTtgYA6kR6FkCiBjKHz5xHxfsA6NsU1ktMkV5BEuj",
            "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
            "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
            "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
            "D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf",
            "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
            "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
            "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "HYz1naua3Qo4M1SJEPAsZLV9yUfqHoi4FRDwjf6g87bL",
            "J7hnE4PRq7T6sbLTJpiKEPgumMZcMc63bhXD8usiWA4V",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "AHtazSEVzTZEm7wsStqGoEVxP6tqFATNuMKXDmwWqqm4",
            "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
            "4PdcTtgYA6kR6FkCiBjKHz5xHxfsA6NsU1ktMkV5BEuj",
            "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo"
          ],
          "data": "PrpFmsY4d26dKbdKMAXs4o3rwzVCKdCWXP3fQuf2BRhHgETq",
          "programId": "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
          "stackHeight": null
        },
        {
          "parsed": {
            "info": {
              "account": "HhEBntRQGzaFBcav3wkCMk16pwHd8aHG1dCnJNF8Rom3",
              "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
              "source": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
              "systemProgram": "11111111111111111111111111111111",
              "tokenProgram": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              "wallet": "ZG98FUCjb8mJ824Gbs6RsgVmr1FhXb2oNiJHa2dwmPd"
            },
            "type": "createIdempotent"
          },
          "program": "spl-associated-token-account",
          "programId": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
          "stackHeight": null
        },
        {
          "parsed": {
            "info": {
              "authority": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
              "destination": "HhEBntRQGzaFBcav3wkCMk16pwHd8aHG1dCnJNF8Rom3",
              "mint": "KnekM3v5WsqvJ6NdZLPvEBeueBMH8iNfWBcHi8r1KGA",
              "source": "4PdcTtgYA6kR6FkCiBjKHz5xHxfsA6NsU1ktMkV5BEuj",
              "tokenAmount": {
                "amount": "14504576",
                "decimals": 6,
                "uiAmount": 14.504576,
                "uiAmountString": "14.504576"
              }
            },
            "type": "transferChecked"
          },
          "program": "spl-token",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "stackHeight": null
        },
        {
          "parsed": {
            "info": {
              "account": "JAFY1yzEBRtznuGoomffBYux4zfq1EwWkh8wP5WRHQK6",
              "destination": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo",
              "owner": "2N9io9YyWirVHGddTSos7a5Z2Fa9hWcnngVXctZ8Gedo"
            },
            "type": "closeAccount"
          },
          "program": "spl-token",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "stackHeight": null
        }
      ],
      "recentBlockhash": "4dsoeJFRq9p83pGAbGQ2mbF13RP7v6jLFKks8wYGg54P"
    },
    "signatures": [
      "4KHPmpbkv28HfhzR1gM1szgtpqg2CLhQo4eo1tD8qctWE4ULYw7fPKuNWPwJjszdq3qin526dC3iYBhcYbragwou"
    ]
  },
  "version": 0
}